README.md

* Correcitng variable descriptions for Sentry oauth 
* Adding steps for accessing Claude developer menu 
* Correcting Authorized URI to match Sentry UI

Accuracy fixes in readme

---

.github/workflows/eval.yml
.vscode/settings.json
package.json
pnpm-lock.yaml
src/evals/utils.ts
src/evals/workflow.eval.ts
src/mcp/tools.ts
vitest.config.ts

Add the following to .env:
- `OPENAI_API_KEY`
- `SENTRY_AUTH_TOKEN`
And then run:
```
pnpm eval:dev
```
Fixes GH-30

Add basic eval scaffolding

---

.github/workflows/eval.yml
.vscode/settings.json
package.json
pnpm-lock.yaml
src/evals/workflow.eval.ts
src/lib/sentry-msw.ts
src/mcp/start-stdio.ts
tsconfig.json

feat: Mock Sentry in evals

---

src/mcp/server.ts
src/mcp/tools.test.ts
src/mcp/transports/cloudflare-worker.ts
src/mcp/types.ts
src/worker/index.ts

- Bind userId from oAuth session when available
- Wrap tool calls in rpc semantics

feat: Improve Sentry instrumentation within tool calls

---

src/worker/auth.ts
src/worker/types.ts

Future proof us so we can request new scopes.
Refs #24, #50

feat: Store scope with OAuth context

---

src/evals/utils.ts
src/mcp/start-stdio.ts

fix: Correct behavior with stdio and mocks

---

packages/mcp-server/src/api-client/client.ts
packages/mcp-server/src/api-client/schema.ts
packages/mcp-server/src/server.ts

feat: Propagate API errors upstream

---

packages/mcp-server-evals/src/evals/list-issues.eval.ts
packages/mcp-server-mocks/src/index.ts

Add invalid project eval

---

.craft.yml
.github/workflows/merge-jobs.yml
.github/workflows/release.yml
bin/bump-version.sh
package.json
packages/mcp-cloudflare/package.json
packages/mcp-server-evals/package.json
packages/mcp-server-mocks/package.json
packages/mcp-server/package.json
pnpm-lock.yaml

feat: Add packaging workflows

---

README.md
packages/mcp-server/README.md

Update stdio instructions to use npx

---

README.md
packages/mcp-server/README.md
packages/mcp-server/src/index.ts

- Suggest latest
- Replace start-stdio with package name

Improvements for stdio

---

.github/workflows/merge-jobs.yml
package.json
packages/mcp-cloudflare/components.json
packages/mcp-cloudflare/package.json
packages/mcp-cloudflare/src/client/App.tsx
packages/mcp-cloudflare/src/client/components/ui/accordion.tsx
packages/mcp-cloudflare/src/client/components/ui/base.tsx
packages/mcp-cloudflare/src/client/components/ui/button.tsx
packages/mcp-cloudflare/src/client/components/ui/code-snippet.tsx
packages/mcp-cloudflare/src/client/components/ui/note.tsx
packages/mcp-cloudflare/src/client/index.css
packages/mcp-cloudflare/src/client/lib/utils.ts
packages/mcp-cloudflare/tsconfig.client.json
packages/mcp-cloudflare/vite.config.ts
pnpm-lock.yaml

This primarily a set of visual changes to make it easier to consume docs.

feat: Overhaul docs

---

packages/mcp-cloudflare/src/server/oauth.ts
packages/mcp-server-tsconfig/package.json
packages/mcp-server/package.json

feat: Improve logging for oauth failures

---

packages/mcp-cloudflare/src/server/index.ts
packages/mcp-server/package.json
packages/mcp-server/src/index.ts
pnpm-lock.yaml

- Remove environment (not working in prod)
- Add Sentry to stdio package

feat: Improve Sentry instrumentation

---

packages/mcp-server/src/api-client/schema.ts

Handle missing units attribute

---

packages/mcp-cloudflare/src/server/auth.ts
packages/mcp-cloudflare/src/server/index.ts
packages/mcp-cloudflare/wrangler.jsonc

Primary fix is compat date revert

Correct oauth behavior

---

packages/mcp-cloudflare/src/server/index.ts
packages/mcp-cloudflare/wrangler.jsonc
packages/mcp-server/src/index.ts
packages/mcp-server/tsdown.config.ts

- Add environment to stdio
- Bind cloudflare as env in workers

Better environment bindings for Sentry

---

packages/mcp-cloudflare/src/client/components/fragments/stdio-setup.tsx
packages/mcp-cloudflare/src/client/index.css

- Wrap pre text (avoids scrolling issues generally)
- Split up stdio command

Improve mobile display

---

packages/mcp-server/src/api-client/client.ts

Refs REMOTE-MCP-DX5, REMOTE-MCP-DX4

Improve error message for multi-project perms

---

packages/mcp-cloudflare/package.json
packages/mcp-server-mocks/src/index.ts
packages/mcp-server-tsconfig/package.json
packages/mcp-server/src/api-client/client.ts
packages/mcp-server/src/api-client/schema.ts
packages/mcp-server/src/schema.ts
packages/mcp-server/src/toolDefinitions.ts
packages/mcp-server/src/tools.test.ts
packages/mcp-server/src/tools.ts

Support regions on API calls

---

packages/mcp-cloudflare/wrangler.jsonc
packages/mcp-server/tsdown.config.ts

Switch to using production-defined config so we can restrict our DSN (to avoid confusing reporting from forks).

Dont overwrite config vars

---

packages/mcp-server-evals/src/evals/get-issue.eval.ts
packages/mcp-server-mocks/src/index.ts
packages/mcp-server/src/api-client/client.ts
packages/mcp-server/src/internal/formatting.ts
packages/mcp-server/src/toolDefinitions.ts
packages/mcp-server/src/tools.test.ts
packages/mcp-server/src/tools.ts

Support event ID lookups on get_issue_details

---

packages/mcp-server/src/server.ts

- Add mcp params
- Explicit status binding

Improve span instrumentation

---

packages/mcp-server/src/internal/issue-helpers.ts

This reverts commit 46b9b23914e8fbfe0b4fb1e2bbad168e829489b9.

Revert "feat: Validate issue ID format (#194)"

---

packages/mcp-cloudflare/package.json
packages/mcp-cloudflare/src/server/lib/mcp-transport.ts
packages/mcp-server/package.json
packages/mcp-server/src/internal/issue-helpers.ts
pnpm-lock.yaml

Fucked this up due to the multi step flow oops

Revert Sentry SDK

---

packages/mcp-cloudflare/src/server/routes/sentry-oauth.ts

Love security "researchers".
Fixes MCP-SERVER-E0V

fix: Dont error on invalid state

---

packages/mcp-server/src/schema.ts
packages/mcp-server/src/toolDefinitions.ts

fix: Coerce cases where possible

---

packages/mcp-server/README.md

(fix) typo

---

packages/mcp-server-evals/src/evals/list-issues.eval.ts
packages/mcp-server-evals/src/evals/utils.ts
packages/mcp-server-mocks/src/index.ts
packages/mcp-server/src/schema.ts
packages/mcp-server/src/toolDefinitions.ts

- Correct now-invalid test in list-issues
- Improve eval system prompt
- Add missing HTTP fixture that _may_ get called
- Trim whitespace on string params as LLMs are imperfect

Improve reliability of evals

---

packages/mcp-server/src/api-client/client.ts
packages/mcp-server/src/internal/issue-helpers.test.ts
packages/mcp-server/src/internal/issue-helpers.ts
packages/mcp-server/src/tools.ts

Fixes MCP-SERVER-DXR, MCP-SERVER-DXW, MCP-SERVER-E1J, MCP-SERVER-E0X, MCP-SERVER-E00, MCP-SERVER-E2V, MCP-SERVER-E1X

Some various minor fixes via MCP

---

.cursor/rules/coding-practices.mdc
.cursorrules

*   The `.cursorrules` file was removed to streamline rule management.
*   The `coding-practices.mdc` file was updated to eliminate duplicated content and improve cross-referencing:
*   A "Related Guidelines" section was added at the top, directing to specific guides like `adding-new-tools.mdc` and `adding-new-prompts.mdc`.
*   The detailed "Tool Development" section was replaced with a concise summary pointing to the `adding-new-tools` guide.
*   The "Prompt Development" section was similarly updated to reference the `adding-new-prompts` guide.
*   This refactoring ensures `coding-practices.mdc` focuses on general coding practices, while comprehensive, specific instructions for tool and prompt development are maintained in their dedicated files, reducing redundancy and enhancing …

Improve Cursor .mdc rule files

---

packages/mcp-cloudflare/src/client/components/fragments/stdio-setup.tsx

Cursor has updated the names of these items in the settings

Update Cursor MCP server installation instructions

---

CLAUDE.md
README.md
packages/mcp-cloudflare/package.json
packages/mcp-server/README.md
packages/mcp-server/package.json
pnpm-workspace.yaml

Add context for Claude Code, and run through recognized fixes.

Initial Claude Code run

---

packages/mcp-server/src/tools.ts

Adding missing states to the exit polling and fixing bug on how status checks are polled which was causing existing status checks to be missed.

Fix: issue fix status handling and missing states

---

codecov.yml

Disable Codecov PR comments to stop coverage statistics updates.
---
[Slack Thread](https://sentry.slack.com/archives/C08J1NSPU6S/p1752515659575879?thread_ts=1752515659.575879&cid=C08J1NSPU6S)

Disable codecov pull request comments

---

packages/mcp-server/src/tools/search-events/agent.ts

- Fix AI_NoObjectGeneratedError by handling UserInputError in search-events AI tools
- Prevent malformed JSON responses when Sentry API permission errors occur
- Add try-catch blocks to `createOtelLookupTool` and `createDatasetAttributesTool` 
- Catch `UserInputError` exceptions and return them as parseable error strings
- Preserve the original error messages from UserInputError for better context
This prevents the JSON parsing errors that were occurring when 403 permission errors were thrown during AI tool execution. The tools now return error messages that the AI agent can understand and either retry with different parameters or pass meaningful errors back to the user.
The fix was implemented by wrapping the tool execution in try-catch blocks that specifically handle `UserInputError` …

fix: handle UserInputError in search-events AI tools

---

packages/mcp-server/src/tools/search-events/agent.ts

The `search_events` tool's AI agent was generating invalid SQL-like syntax in queries, causing search failures. This PR fixes the issue by updating the system prompts to explicitly prevent SQL syntax generation.
- Updated AI agent prompts in `search_events/agent.ts` to prevent SQL-like query generation
- Removed confusing SQL terminology from system prompts that was causing the AI to generate queries like `timestamp >= yesterday()` and `gen_ai.usage.input_tokens IS NOT NULL`
- Added explicit warnings against using SQL functions and syntax
- Added concrete examples showing correct Sentry patterns vs incorrect SQL patterns
- Enhanced error correction feedback to specifically mention SQL syntax issues
The AI agent now correctly generates:
- `has:gen_ai.usage.input_tokens` instead of …

fix: prevent search_events from generating SQL-like syntax

---

packages/mcp-cloudflare/src/server/routes/sentry-oauth.ts

Catches and logs invalid redirect URI errors without sending them to Sentry, preventing noise from OAuth scan attempts. Other errors are still properly reported.
Fixes MCP-SERVER-E05

fix: suppress Sentry reporting for invalid redirect URI errors

---

packages/mcp-server/src/resources.test.ts
packages/mcp-server/src/resources.ts
packages/mcp-server/src/resources/about.ts
packages/mcp-server/src/resources/index.ts

Adds a new MCP resource at sentry://about that provides comprehensive documentation about the Sentry MCP service, its capabilities, and common developer workflows. This helps users discover what they can do with the service.
Changes:
- Add new about-content.ts with detailed service documentation
- Add aboutHandler to resources.ts for the sentry://about URI
- Add tests for the new about resource
- Include information about AI-powered tools, debugging workflows, and real-world use cases

feat: add sentry://about resource for user discovery (#472)

---

packages/mcp-cloudflare/src/client/instrument.ts
packages/mcp-cloudflare/src/server/sentry.config.ts
packages/mcp-server/src/index.ts
pnpm-lock.yaml
pnpm-workspace.yaml

This reverts commit 971ca71f8c7c874f09d6b2efedd283531712c33d.

Revert "feat: downgrade Sentry to v9.45.0 for stability (#478)"

---

pnpm-lock.yaml
pnpm-workspace.yaml

Updates OAuth provider package version in workspace configuration.

chore: bump @cloudflare/workers-oauth-provider to ^0.0.6

---

packages/mcp-cloudflare/src/server/app.ts
packages/mcp-cloudflare/src/server/lib/approval-dialog.test.ts
packages/mcp-cloudflare/src/server/lib/approval-dialog.ts
packages/mcp-cloudflare/src/server/routes/sentry-oauth.ts

This PR adds comprehensive CSRF (Cross-Site Request Forgery) token protection to the OAuth approval dialog in the Sentry MCP Cloudflare package.
- CSRF Token Generation: Cryptographically secure random tokens with embedded timestamps
- Secure Cookie Storage: HTTP-only, Secure, SameSite=Strict cookies for token storage
- Form Protection: Hidden CSRF token field in the approval form
- Token Validation: Server-side verification with constant-time comparison to prevent timing attacks
- Automatic Cleanup: CSRF tokens are cleared after successful validation to prevent reuse
- Timestamp Validation: Tokens expire after 1 hour for enhanced security
- Generates 32-character tokens (8 chars timestamp + 24 chars random)
- Uses crypto.getRandomValues() for cryptographically secure randomness
- …

Add CSRF token protection to OAuth approval dialog

---

.env.example
packages/mcp-cloudflare/.env.example

- Add root .env.example with OpenAI API key and Spotlight settings
- Add packages/mcp-cloudflare/.env.example with OAuth and web app configuration

Add example environment configuration files

---

packages/mcp-cloudflare/package.json
packages/mcp-cloudflare/src/client/components/fragments/remote-setup.tsx
packages/mcp-cloudflare/src/client/components/fragments/stdio-setup.tsx
packages/mcp-cloudflare/src/client/components/ui/json-schema-params.tsx
packages/mcp-cloudflare/src/client/components/ui/template-vars.tsx
packages/mcp-server-tsconfig/package.json

rest of the changes are from `biome format` and `biome lint:fix`

feat(docs) add Codex config
