src/lib/sentry-api.ts, src/mcp.ts
Adds create team and list projects endpoints (currently unused). 
Additionally cleans out MCP output handling. 
Fixes GH-6
=> Expand api

src/routes/home.tsx
VSCode added support for MCPs in v1.99. This PR adds instructions for it.
Note: VSCode supports remote MCPs but does not support automatic authentication flow yet so we go through `npx mcp-remote` path still.
=> feat(docs): Add instructions for VSCode

README.md, package.json, src/index.ts, src/mcp/server.ts, src/mcp/start-stdio.ts, src/mcp/tools.ts, src/mcp/transports/cloudflare-worker.ts, src/mcp/transports/stdio.ts, src/routes/auth.ts, src/routes/home.tsx, src/types.ts, tsconfig.json, wrangler.jsonc
Implements a basic stdio wrapper (requiring SENTRY_AUTH_TOKEN locally).
This will still need a distro to get this into GA, but works against dev.
Refs GH-28
=> Initial work on stdio

src/evals/get-issue.eval.ts, src/evals/list-issues.eval.ts, src/evals/list-releases.eval.ts, src/lib/sentry-api/client.ts, src/lib/sentry-api/schema.ts, src/lib/sentry-msw.ts, src/mcp/schema.ts, src/mcp/tools.test.ts, src/mcp/tools.ts
- Add `list_releases`
- Expand `list_issues` context to improve responses
- Rename REMOTE-MCP to CLOUDFLARE-MCP to align fixtures
=> Expand tools

packages/mcp-cloudflare/package.json, packages/mcp-server-evals/package.json, packages/mcp-server/package.json, packages/mcp-server/src/version.ts, pnpm-lock.yaml
9.15.0 is breaking cloudflare
```
3:24:55 PM [vite] Internal server error: Cannot read from private field
@sentry/mcp-cloudflare:dev:       at async ProxyServer.fetch (file:///home/dcramer/src/sentry-mcp/node_modules/.pnpm/miniflare@4.20250428.0/node_modules/miniflare/src/workers/core/proxy.worker.ts:173:11)
^C    ...Finishing writing to cache...   
```
=> Revert sentry upgrade

packages/mcp-server-mocks/src/index.ts, packages/mcp-server/src/api-client/client.ts, packages/mcp-server/src/tools.test.ts
This should remove any complexity around the multi-project select behaviors, which seem to not totally be implemented correctly (from a feature flag conditions pov) upstream.
Refs #155
=> feat: Swap to project specific endpoint for listIssues

packages/mcp-server/src/api-client/schema.ts, packages/mcp-server/src/internal/issue-helpers.test.ts, packages/mcp-server/src/internal/issue-helpers.ts, packages/mcp-server/src/tools.ts
LLMs arent always going to nail what we need from a parameter inputs, so this massages one known failure situation where the LLM passed the issueId including a trailing period.
=> Remove trailing punctuation from issue IDs

packages/mcp-server/src/server.ts
The API will regularly return valid errors ("you dont have this feature").
To handle that, and avoid noise, we're just going to see they're _all_ valid, and return them to the client without capturing them.
=> Only capture issues for unknown errors

packages/mcp-cloudflare/src/server/lib/mcp-transport.ts, packages/mcp-cloudflare/src/server/sentry.config.ts, packages/mcp-server/src/index.ts
- mcp_server_version => mcp.server_version
- mcp.transport (only on stdio atm)
- sentry.host
=> Expand global context

packages/mcp-server/src/tools.ts
This was breaking effectively all self-hosted installs where the parsed host ended up being 'https'.
Fixes MCP-SERVER-DXC
=> fix: Parse domain from regionUrl

packages/mcp-server/src/version.ts
This reverts commit b22af6e68c31d3cffd40ddd3612b8f57dca11dcc.
This change appears to not even be correct, but reverting dep bumps allows us to restore this.
=> Revert "fix: Handle undefined process (#188)"

packages/mcp-server/src/api-client/client.ts
Avoid using console.log in stdio as stdout is used for the transport communication.,
Fixes GH-190
=> fix: Move logging into Sentry

packages/mcp-server-evals/src/evals/get-issue.eval.ts, packages/mcp-server-mocks/src/index.ts, packages/mcp-server/src/api-client/client.ts, packages/mcp-server/src/api-client/schema.ts, packages/mcp-server/src/tools.test.ts, packages/mcp-server/src/tools.ts
This change is considered temporary, as we need to resolve the upstream organization querying behavior to not require multiple hops. That likely will take a bit, so for now we're going to just eat the cost here.
Fixes #227
=> Query all regions for a users organizations

.cursor/rules/coding-practices.mdc, .cursor/rules/using-api-mocks.mdc
A new rule file, `using-api-mocks.mdc`, was created to document the API mocking system. This guide focuses on the Mock Service Worker (MSW) implementation for the Sentry API.
The `using-api-mocks.mdc` guide covers:
*   **JSON Fixtures**: Details on organizing and using data from `packages/mcp-server-mocks/src/fixtures/` for mock responses, including patterns for variations and dynamic data.
*   **Route Definition Patterns**: Examples for defining GET, POST/PUT routes, handling path parameters, and processing request bodies.
*   **Request Validation Patterns**: Guidance on extracting and validating query parameters (e.g., `dataset`, `sort`, complex `query` strings) and returning appropriate HTTP status codes.
*   **Error Response Patterns**: Demonstrates returning validation errors (e.g., …
=> Create using-api-mocks documentation

packages/mcp-cloudflare/vite.config.ts, packages/mcp-cloudflare/wrangler.jsonc
Vite expects the public directory to be found at `./public`, but that is not where the directory exists currently. This can be seen when visiting https://mcp.sentry.dev/ and the favicon fails to load
It can also be seen when running an Open Graph meta tags check like so: https://www.opengraph.xyz/url/https%3A%2F%2Fmcp.sentry.dev
This pull request explicitly sets the `public` directory for Vite and Cloudflare to it's current location so that the images now resolve as expected.
=> fix: set explicit public directory path for Vite

docs/monitoring.mdc
we were mentioning Sentry's discontinued metrics product
=> chore: remove outdated custom metrics examples from monitoring doc

.github/workflows/bug-prediction.yml
Add overwatch bug predictor github workflow to this repo to enable the alpha feature.
Note that this feature is currently being merged with the AI PR review feature (work tracked [here](https://linear.app/getsentry/project/25q2-error-prediction-becomes-a-ai-pr-review-feature-60c79fb6bcf8/issues)). 
Once that project is completed, this github action workflow can be removed (this cleanup task is tracked [here](https://linear.app/getsentry/issue/PREVENT-168)).
Also note I created a token and added a secret to this repo to enable this feature (`OVERWATCH_SENTRY_AUTH_TOKEN`). This can also get cleaned up with above when ready.
=> feat: add overwatch bug prediction gh workflow

packages/mcp-server-mocks/src/fixtures/event-attachments.json, packages/mcp-server-mocks/src/index.ts, packages/mcp-server/package.json, packages/mcp-server/src/api-client/client.ts, packages/mcp-server/src/api-client/schema.ts, packages/mcp-server/src/api-client/types.ts, packages/mcp-server/src/schema.ts, packages/mcp-server/src/server.ts, packages/mcp-server/src/tools/get-event-attachment.test.ts, packages/mcp-server/src/tools/get-event-attachment.ts, packages/mcp-server/src/tools/index.ts, packages/mcp-server/src/tools/types.ts, packages/mcp-server/src/types.ts
includes #346 updated to work w/ the tool modularization
=> add event attachment download support 

.claude/commands/gh-pr.md, .claude/commands/gh-review.md, .claude/settings.json
- Add custom Claude commands for managing pull requests with proper conventions
- Include Claude settings file with appropriate MCP permissions
- Enable streamlined PR workflows through `/gh-pr` and `/gh-review` commands
- **New feature**: Added `/gh-pr` command for creating/updating pull requests
- **New feature**: Added `/gh-review` command for addressing PR feedback and status checks
- **Configuration**: Added Claude settings with MCP permissions for Sentry integration
These commands help maintain consistent PR practices and integrate with the GitHub CLI workflow.
=> feat: add Claude commands for PR management

packages/mcp-server/src/tools/search-events.test.ts, packages/mcp-server/src/tools/search-events/CLAUDE.md, packages/mcp-server/src/tools/search-events/agent.ts, packages/mcp-server/src/tools/search-events/config.ts
This PR fixes the user agent query mapping in the search_events tool. Previously, queries about "user agents" were incorrectly being mapped to `user.id` fields instead of the correct `user_agent.original` field that contains the actual browser/client string.
- Updated AI agent prompts to correctly map "user agents", "browsers", and "clients" to `user_agent.original`
- Added explicit guidance to use the datasetAttributes tool for ambiguous field names
- Prevents incorrect aggregation by user IDs when users ask about browser/client statistics
- Added user agent query examples for spans dataset (e.g., "which user agents have the most tool calls")
- Added user agent examples for errors dataset (e.g., "errors by browser")
- Demonstrates proper use of `has:user_agent.original` filtering
- Added …
=> fix: correct user agent field mapping in search_events tool

.github/workflows/onlyrobots.yml
- Adds the missing `checks:write` permission to the OnlyRobots GitHub Action workflow
- Removes the unnecessary `issues:write` permission
The OnlyRobots action requires `checks:write` permission to create GitHub check runs, but our workflow was missing this permission. According to the [OnlyRobots README](https://github.com/getsentry/action-onlyrobots/blob/main/README.md), the required permissions are:
- `contents: read`
- `pull-requests: write`
- `checks: write` ← This was missing
We also had `issues:write` which is not required by the action.
- Added `checks: write` to the permissions section
- Removed `issues: write` as it's not needed
The OnlyRobots action should now be able to create check runs on pull requests without permission errors.
=> fix: add missing checks:write permission to OnlyRobots workflow

.github/workflows/onlyrobots.yml
This PR enables comment functionality in the OnlyRobots GitHub Action workflow and updates the action version to v1.2.0.
- **Feature**: Added `post-comment: true` parameter to enable humorous comments when human-written code is detected in PRs
- **Update**: Bumped OnlyRobots action version from v1.1.0 to v1.2.0 to ensure we're using the latest version and bust any caches
These changes will make the OnlyRobots integration more engaging by providing informative feedback directly in pull requests when non-AI-generated code is detected.
=> feat: enable OnlyRobots comments and update to v1.2.0

.github/workflows/onlyrobots.yml
- Update OnlyRobots GitHub Action from pinned version v1.2.0 to v1 tag for automatic updates
- Testing GitHub Actions cache busting for the v1 tag
- Modified `.github/workflows/onlyrobots.yml` to use `getsentry/action-onlyrobots@v1` instead of `@v1.2.0`
- This allows the workflow to automatically receive patch and minor updates within the v1 major version
- The v1 tag exists and includes the dist/index.js file, but there may be a cache issue preventing it from being found
=> chore: update OnlyRobots action to use v1 tag

packages/mcp-server/src/tools/search-events/handler.ts
- Add guidance hints to help LLMs parse org/project notation directly in search_events tool
- Prevent unnecessary find_organizations and find_projects API calls when using org/project format
This PR adds a `<hints>` section to the search_events tool description that instructs LLMs to:
1. Recognize `name/otherName` format as `<organizationSlug>/<projectSlug>`
2. Parse this notation directly without making additional API calls
This follows the same pattern used in other tools like `find_dsns` and addresses the inefficiency reported in #393.
Fixes #393
=> fix: add hints for org/project notation in search_events tool

.claude/settings.json, packages/mcp-server/src/toolDefinitions.json
- Added GitHub CLI commands (`gh pr checks`, `gh pr view`, `gh run view`) to Claude settings allow list for better PR and workflow run visibility
- Included auto-generated `toolDefinitions.json` file that contains JSON schemas for all MCP server tools
The `.claude/settings.json` now includes permissions for GitHub CLI commands to enable viewing PR checks and run statuses directly from the CLI. The `toolDefinitions.json` file is auto-generated and provides structured tool definitions for the MCP server.
=> feat: add GitHub CLI permissions and auto-generated tool definitions

.github/workflows/deploy.yml
- Fixes sourcemap upload to Sentry during production builds by adding the missing `SENTRY_AUTH_TOKEN` environment variable to the GitHub Actions deploy workflow
The Sentry Vite plugin was configured correctly but couldn't upload sourcemaps during CI builds because the authentication token wasn't available. This prevented proper error tracking and debugging in production.
- Ensure `SENTRY_AUTH_TOKEN` secret is configured in GitHub repository settings
- Deploy to production will now successfully upload sourcemaps to Sentry
- Production errors will show proper stack traces with source code context
=> fix: add SENTRY_AUTH_TOKEN to deploy workflow for sourcemap uploads

packages/mcp-server/src/tools/search-events.test.ts, packages/mcp-server/src/tools/search-events/agent.ts
Improve the search_events agent's robustness by adding better error handling and enabling multiple sequential tool calls for complex queries.
- Wrap `experimental_output` access in try-catch to handle `AI_NoObjectGeneratedError` gracefully
- Return safe error objects instead of throwing exceptions when AI parsing fails
- Make `query` field optional in `QueryTranslationResult` interface (not needed when there's an error)
- Simplify error responses to only include the `error` field
- Add `maxSteps: 5` to the `generateText` call to allow up to 5 sequential tool calls
- This enables the AI to gather information through multiple tools before generating the final query
- Enhanced `mockAIResponse` helper to accept custom sort and timeRange parameters
- Fixed test that was using an incorrect mock …
=> fix: improve error handling and add maxSteps to search_events agent

packages/mcp-cloudflare/src/client/components/chat/chat.tsx, packages/mcp-cloudflare/src/client/contexts/auth-context.tsx, packages/mcp-cloudflare/src/client/hooks/use-mcp-metadata.ts, packages/mcp-cloudflare/src/server/lib/html-utils.ts, packages/mcp-cloudflare/src/server/routes/chat-oauth.ts, packages/mcp-cloudflare/src/server/routes/chat.ts, packages/mcp-cloudflare/src/server/types/chat.ts
This PR implements automatic token refresh for the MCP Cloudflare demo, eliminating the need for users to re-authenticate when their tokens expire. The implementation moves from localStorage-based token storage to secure httpOnly cookies for improved security.
- **Automatic token refresh**: When a 401 error occurs, the server automatically attempts to refresh the token using the stored refresh token, then retries the request
- **Cookie-based authentication**: All tokens are now stored in secure httpOnly cookies instead of localStorage, preventing XSS attacks
- **Zero user interruption**: Token refresh happens transparently server-side without any user interaction required
- Authentication is now entirely cookie-based; users will need to re-authenticate once after deployment
- Removed the …
=> feat: implement automatic token refresh with cookie-based authentication

packages/mcp-server-evals/src/evals/search-events.eval.ts, packages/mcp-server/src/tools/search-events/agent.ts
The search_events tool's AI agent now properly handles queries containing "me" references by instructing users to first call the whoami tool.
- Updated the search_events AI agent prompts to detect "me", "my", "myself", or "affecting me" references
- Agent now returns an instructive error message explaining that the user should first use the 'whoami' tool to get their user ID
- Provides clear guidance on the correct query format after obtaining the user ID (e.g., "user.id:12345")
- Added eval test case for "me" query handling that expects the whoami tool to be called first
Previously, when users queried "errors affecting me", the search_events tool would incorrectly use `user.id:me` which doesn't resolve to anything in Sentry. Now it properly instructs the LLM to orchestrate the tools by …
=> fix: handle 'me' references in search_events

packages/mcp-server/src/tools/search-events/handler.ts, packages/mcp-server/src/tools/search-issues/handler.ts
Fixes error handling to show specific error messages to users instead of generic "problem communicating with the Sentry API" messages.
- Use `UserInputError` instead of generic `Error` for project not found errors in both `search-issues` and `search-events` tools
- Use `UserInputError` for query translation failures in `search-events` tool
- Server error handler now properly recognizes these as user input errors and displays the actual error message
**Before**: "It looks like there was a problem communicating with the Sentry API."
**After**: "Project 'sentry-mcp' not found in organization 'sentry'"
Fixes MCP-SERVER-ED7
=> fix: propagate specific error messages to users instead of generic API errors

packages/mcp-cloudflare/src/client/components/ui/header.tsx
Simple fix to remove the versioning withing the header component. No need to have it and it currently shows 0.0.0 which feel like a bug.
**Now you see it**
**Now you dont**
=> Removing the versioning callout to the header component. 

packages/mcp-server/src/tools/search-events/agent.ts, packages/mcp-server/src/tools/search-events/handler.ts
- Adds runtime validation to ensure the sort field is always included in the fields array for search_events queries
- Returns clear error messages for self-correction when validation fails
- Fixes MCP-SERVER-ECJ error caused by missing sort field in Sentry API queries
Fixes MCP-SERVER-ECJ
The search_events tool was generating queries where the sort field wasn't included in the selected fields, causing Sentry API errors. This fix adds validation to catch this issue and provide clear feedback to the AI agent.
- Added validation in `handler.ts` that checks if the sort field exists in the fields array
- Enhanced agent instructions in `agent.ts` with stronger requirements and validation steps
- Added a concrete example for "X values" queries to demonstrate proper field selection
- Replaced …
=> fix: add validation to ensure sort field is included in search_events fields array

docs/adding-tools.mdc, docs/architecture.mdc, packages/mcp-server/src/agent-tools/lookup-otel-semantics.ts, packages/mcp-server/src/tools/search-events/CLAUDE.md, packages/mcp-server/src/tools/search-events/agent.ts, packages/mcp-server/src/tools/search-events/handler.ts, packages/mcp-server/src/tools/search-events/utils.ts, packages/mcp-server/src/tools/search-issues/CLAUDE.md, packages/mcp-server/src/tools/search-issues/agent.ts, packages/mcp-server/src/tools/search-issues/handler.ts
This PR refactors the AI-powered search tools (`search_events` and `search_issues`) to improve performance through static prompts and better code organization.
- **Static prompts for LLM caching**: Removed dynamic prompt modification to enable LLM provider caching, reducing latency and costs
- **Extracted reusable tool helpers**: Moved `createOtelLookupTool` and `createDatasetAttributesTool` to shared modules for better reusability
- **Removed retry mechanisms**: Both search tools now follow cleaner MCP patterns where tools return errors for upstream agents to handle
- **Consolidated tool creation**: ~130 lines of duplicate code removed by extracting tool creation helpers to appropriate modules
- **Comprehensive documentation**: Added CLAUDE.md files for both AI-powered tools documenting …
=> refactor: make agent prompts static for LLM caching and extract tool helpers

packages/mcp-server/src/tools/search-events.test.ts, packages/mcp-server/src/tools/search-events/handler.ts
- Fixed error handling in `search_events` tool to properly handle unsupported time series queries
- Changed from throwing generic `Error` to `UserInputError` for better MCP protocol compliance
- Added test coverage for time series query rejection
The `search_events` tool was failing at the infrastructure level when users requested time series aggregations (e.g., "requests to tools over time"). The AI agent correctly identified these as unsupported but the handler threw a generic JavaScript Error, causing complete tool execution failure.
This change ensures proper error propagation through the MCP protocol, allowing calling agents to handle the limitation gracefully and potentially suggest alternative queries.
Fixes MCP-SERVER-ECH
_Created using Claude Code_
=> fix: use UserInputError for unsupported time series queries in search_events

packages/mcp-server/src/tools/search-events/agent.ts, packages/mcp-server/src/tools/search-issues/config.ts
- Fixed AI agents incorrectly including sort syntax in the query field
- Made system prompts explicit about sort parameter separation
- Unified sorting rules structure between search_issues and search_events agents
The AI agents for `search_issues` and `search_events` were sometimes incorrectly including sort syntax (e.g., `sort:user`) in the query field instead of using the separate sort parameter. This caused malformed queries like:
```json
{"query": "is:unresolved sort:user", "sort": "user"}
```
- Updated system prompts to explicitly state that sort MUST go in the separate "sort" field
- Added clear WRONG vs CORRECT examples to prevent confusion
- Unified the sorting rules structure between both agents for consistency
- Reduced redundant examples while keeping key patterns clear
This …
=> fix: prevent LLM from duplicating sort parameters in query field

packages/mcp-server/src/tools/search-events/formatters.ts, packages/mcp-server/src/tools/search-issues/formatters.ts
Add structured logging when search-events or search-issues return no results. This helps monitor search patterns and understand user queries that yield empty results.
- Add Sentry.logger.info() calls with structured context when no results are found
- Log natural language query, translated query, fields, organization, and dataset information
- Apply to all three search-events formatters (errors, logs, spans) and search-issues formatter
Uses Sentry's modern logging API with the `logger.fmt` template tag for structured logging. The logs are at info level since empty results are expected scenarios, not errors.
---
_PR created with Claude Code_
=> feat: add logging for empty search results

packages/mcp-cloudflare/src/server/routes/chat.ts, packages/mcp-test-client/src/mcp-test-client-remote.ts, packages/mcp-test-client/src/mcp-test-client.ts
Add descriptive names to MCP clients to distinguish between different implementations and improve monitoring/debugging capabilities.
- **Web client**: Change from `"sentry"` to `"mcp.sentry.dev (web)"`
- **Test client (remote)**: Change from `"sentry-mcp"` to `"mcp.sentry.dev (test-client)"`
- **Test client (local)**: Add name `"mcp.sentry.dev (test-client)"` (previously unnamed)
- Clear identification of client type in logs and monitoring
- Consistent naming scheme across all implementations
- Better debugging experience when analyzing MCP connections
- Domain-based naming that reflects the service
---
_PR created with Claude Code_
=> feat: improve MCP client names for better identification

README.md, docs/monitoring.mdc, packages/mcp-cloudflare/src/client/components/fragments/stdio-setup.tsx, packages/mcp-server/README.md, packages/mcp-server/src/constants.ts, packages/mcp-server/src/index.ts, packages/mcp-server/src/server.ts
Improve documentation and configuration handling for AI-powered search tools in the stdio distribution.
- **OPENAI_API_KEY documentation**: Added clear documentation across all setup guides explaining that AI-powered search tools (`search_events` and `search_issues`) require an OpenAI API key
- **Startup warnings**: Added non-blocking startup warning when OPENAI_API_KEY is missing, listing which tools will be unavailable
- **Simplified configuration**: Removed MCP_USER_AGENT environment variable - no longer needed as stdio transport handles this internally
- Removed `MCP_USER_AGENT` environment variable support (was only used for telemetry identification)
- Server identification now uses static constants (`MCP_SERVER_NAME`, `LIB_VERSION`) instead of passing values through context
- …
=> feat: add OPENAI_API_KEY documentation and remove MCP_USER_AGENT

packages/mcp-cloudflare/src/client/instrument.ts, packages/mcp-cloudflare/src/client/utils/sentry-scrubbing.ts, packages/mcp-cloudflare/src/server/sentry.config.ts, packages/mcp-cloudflare/src/server/utils/sentry-scrubbing.ts, packages/mcp-server/src/index.ts, packages/mcp-server/src/internal/sentry-scrubbing.test.ts, packages/mcp-server/src/internal/sentry-scrubbing.ts, packages/mcp-test-client/src/index.ts, packages/mcp-test-client/src/utils/sentry-scrubbing.ts
- Add `sentryBeforeSend` hook to scrub sensitive data from Sentry events before they are sent
- Remove breadcrumbs entirely from all events to prevent sensitive data leakage
- Detect and redact OpenAI API keys, Bearer tokens, and Sentry access tokens
- **Sensitive data detection**: Automatically detects patterns for OpenAI API keys (`sk-*`), Bearer tokens, and Sentry access tokens (`sntrys_*`)
- **Recursive scrubbing**: Deep clones events and recursively scrubs all string values in messages, exceptions, contexts, extra data, and tags
- **Console logging**: Logs to `console.error` when sensitive data is detected for monitoring
- **Extensible patterns**: Provides `addScrubPattern()` function to add custom patterns at runtime
Added reusable `sentry-scrubbing.ts` utility across all Sentry …
=> feat: add Sentry event scrubbing to prevent API key exposure

README.md
=> fix: correct typo in README (sever → server)

packages/mcp-server/src/api-client/schema.ts, packages/mcp-server/src/internal/formatting.ts, packages/mcp-server/src/tools/get-issue-details.test.ts
This commit introduces an optional `tags` field to the event schema, allowing for structured tagging of events. Additionally, it implements a new `formatTags` function to format these tags in the event output.
- Added `tags` field to `BaseEventSchema` as an optional array of objects containing `key` and `value` strings.
- Updated `formatEventOutput` to include formatted tags in the output if present.
This enhancement improves the event structure and output readability, facilitating better event categorization and analysis.
Fixes #453
=> feat: add optional tags support to event schema and format output accordingly

packages/mcp-server/src/api-client/client.test.ts, packages/mcp-server/src/api-client/client.ts, packages/mcp-server/src/internal/formatting.ts, packages/mcp-server/src/tools/search-events/formatters.ts, packages/mcp-server/src/tools/search-events/handler.ts, packages/mcp-server/src/tools/search-issues/formatters.ts
Fix broken explorer URLs for spans dataset in the search_events tool.
- Add missing `table=span` parameter required by Sentry UI for spans dataset
- Fix projectId parameter naming (was incorrectly using projectSlug)
- Improve URL display formatting in results (remove emoji, add newline)
- Update tests to use projectId instead of projectSlug
When using the search_events tool, the generated "View in Sentry" URLs were broken due to:
1. Missing `table=span` parameter for spans dataset
2. Incorrect parameter naming (projectSlug vs projectId)
3. Poor formatting of the URL in the output
- Added `table=span` parameter in `buildEapUrl` for spans dataset
- Fixed parameter naming throughout to use projectId consistently
- Improved markdown formatting to display URL on separate line without emoji
- …
=> fix: standardize API client to use console.error for error logging

packages/mcp-server/src/api-client/client.test.ts, packages/mcp-server/src/api-client/client.ts, packages/mcp-server/src/tools/search-events/handler.ts
The getEventsExplorerUrl method was missing support for absolute time ranges (start/end) and custom statsPeriod values, causing search_events tool URLs to always default to 24h period. This fix ensures the generated URLs respect the time parameters from the query.
Fixes #463
=> fix: add missing time parameters to events explorer URLs

packages/mcp-server/src/api-client/client.test.ts, packages/mcp-server/src/api-client/client.ts, packages/mcp-server/src/utils/url-utils.test.ts, packages/mcp-server/src/utils/url-utils.ts
Regional subdomains like us.sentry.io and eu.sentry.io are for API endpoints only. Web UI URLs should always use the base sentry.io domain for SaaS instances.
=> fix: use correct sentry.io domain for web UI URLs with regional API hosts

packages/mcp-cloudflare/src/client/instrument.ts, packages/mcp-cloudflare/src/server/sentry.config.ts, packages/mcp-server/src/index.ts, pnpm-lock.yaml, pnpm-workspace.yaml
- Downgrade @sentry/* packages from v10.2.0 to v9.45.0/v9.34.0
- Move enableLogs to _experiments configuration for server environments
- Update vite-plugin from 4.0.2 to 3.6.1 for compatibility
Fixes MCP-SERVER-EHN
=> feat: downgrade Sentry to v9.45.0 for stability

packages/mcp-server-mocks/src/fixtures/trace-meta-with-nulls.json, packages/mcp-server-mocks/src/index.ts, packages/mcp-server/src/api-client/schema.ts, packages/mcp-server/src/tools/get-trace-details.test.ts, pnpm-lock.yaml
Fixes MCP-SERVER-EFR
The Sentry API can return null values for transaction.event_id when spans are not directly associated with transaction events. Updated the Zod schema to handle these null values and added test coverage with fixtures.
=> fix: Allow nullable transaction.event_id in trace metadata schema

packages/mcp-cloudflare/src/client/components/fragments/remote-setup.tsx
- Temporarily hides the organization/project constraints documentation from the remote setup page
- The subpath-based MCP constraints feature is currently not working correctly
- Commented out the constraints documentation section rather than deleting it
- This makes it easy to restore once the feature is working properly
=> fix(cloudflare): hide project/org constraints documentation

packages/mcp-server/src/internal/agents/tools/dataset-fields.ts, packages/mcp-server/src/internal/agents/tools/otel-semantics.ts, packages/mcp-server/src/internal/agents/tools/whoami.ts, packages/mcp-server/src/tools/search-events/agent.ts, packages/mcp-server/src/tools/search-events/handler.ts, packages/mcp-server/src/tools/search-events/utils.ts, packages/mcp-server/src/tools/search-issues/agent.ts, packages/mcp-server/src/tools/search-issues/handler.ts
Addresses https://github.com/getsentry/sentry-mcp/issues/526 by refactoring embedded agent tools to support `regionUrl` as a passable argument alongside `organizationSlug`.
Issue #526 requested making embedded agent tools support `regionUrl` for multi-region Sentry deployments. The previous architecture required agents to create their own API service, making it difficult to pass region configuration cleanly.
- **searchEventsAgent** and **searchIssuesAgent** now take `apiService` directly in options object
- Pre-bind tools with region-aware API service instead of passing region parameters to tools
- Handlers create region-configured API service and pass to agents
- Updated all `createXTool` functions to use object parameters:
- `createWhoamiTool({apiService})`
- …
=> fix: Pass along regionUrl to embedded tools

packages/mcp-server/src/api-client/client.ts, packages/mcp-server/src/schema.ts, packages/mcp-server/src/tools/find-organizations.ts, packages/mcp-server/src/tools/find-projects.ts, packages/mcp-server/src/tools/find-teams.ts
Add optional query parameter to list endpoints to support filtering by name/slug. Return up to 25 results with clear messaging when limit is hit, directing users to use the query parameter to narrow results.
Changes:
- Added ParamSearchQuery schema for consistent search validation
- Updated API client methods (listOrganizations, listTeams, listProjects) to accept query parameter
- Hardcoded per_page=25 limit in API client (not exposed to callers)
- Updated all three find_* tools to support optional query parameter
- Added warning message when hitting 25 result limit
- Updated tool descriptions to mention search capability and result limits
Fixes #573
=> feat: add search support to find_organizations, find_teams, and find_projects
